Add switch-to-windows command

diff --git a/bin/,remotecontrol b/bin/,remotecontrol
--- a/bin/,remotecontrol
+++ b/bin/,remotecontrol
@@ -6,9 +6,10 @@ readonly usage="Usage: $(basename "$0") [-h|--help] <command>
 Remotely control a computer running a Debian-derived Linux distribution.
 
 Commands:
-	off      Turn off the computer.
-	reboot	 Reboot the computer.
-	suspend	 Put the computer to sleep.
+	off									Turn off the computer.
+	reboot  	 					Reboot the computer.
+	suspend	 						Put the computer to sleep.
+	switch-to-windows		Reboot into the first Grub menuentry that mentions Windows.
 
 Flags:
     -h, --help  show this help text"
@@ -31,6 +32,20 @@ elif [ "$command" = 'reboot' ]; then
 	sudo systemctl reboot
 elif [ "$command" = 'suspend' ]; then
 	sudo systemctl suspend
+elif [ "$command" = 'switch-to-windows' ]; then
+	# awk program inspired by Grub's Bash completion script
+	if ! grub_menuentry_windows="$(
+		awk \
+			--field-separator "[\"']" \
+			'BEGIN{IGNORECASE = 1} /menuentry / { if ($2 ~ "windows") {print $2; exit} }' \
+			/boot/grub/grub.cfg
+	)"; then
+		echo "error: failed to get title of Grub menuentry for Windows"
+		exit 1
+	fi
+
+	sudo grub-reboot "$grub_menuentry_windows"
+	sudo systemctl reboot
 else
 	echo "error: command \"$command\" is not supported"
 	exit 1
