Format with shfmt

diff --git a/bin/check-installed b/bin/check-installed
--- a/bin/check-installed
+++ b/bin/check-installed
@@ -2,18 +2,18 @@
 
 set -euo pipefail
 
-if (( $# < 2 )); then
-  echo "error: must provide name and URL"
-  exit 1
+if (($# < 2)); then
+	echo "error: must provide name and URL"
+	exit 1
 fi
 
 # Check if a program is installed
 # $1: name of command to check for
 # $2: URL for information on installing the command
 if [ -z "$(command -v "$1")" ]; then
-  echo "error: could not find $1, please install it before trying again"
-  if [ -n "$2" ]; then
-    echo "       $2"
-  fi
-  exit 1
+	echo "error: could not find $1, please install it before trying again"
+	if [ -n "$2" ]; then
+		echo "       $2"
+	fi
+	exit 1
 fi
diff --git a/bin/complex-files b/bin/complex-files
--- a/bin/complex-files
+++ b/bin/complex-files
@@ -13,16 +13,16 @@ Flags:
     -h, --help  show this help text"
 
 if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
-  echo "$usage"
-  exit 0
+	echo "$usage"
+	exit 0
 fi
 
 path="${1:-}"
 if [ -z "$path" ]; then
-  echo 'error: must pass a path'
-  exit 1
+	echo 'error: must pass a path'
+	exit 1
 fi
 shift
 
-scc --sort complexity --format json "$@" "$path" | \
-    jq --raw-output 'map(.Files) | flatten | sort_by(.Complexity) | map(.Location) | reverse | limit(10;.[])'
+scc --sort complexity --format json "$@" "$path" |
+	jq --raw-output 'map(.Files) | flatten | sort_by(.Complexity) | map(.Location) | reverse | limit(10;.[])'
diff --git a/bin/create-npm-repo b/bin/create-npm-repo
--- a/bin/create-npm-repo
+++ b/bin/create-npm-repo
@@ -3,8 +3,8 @@
 set -euo pipefail
 
 if ! [ -f package.json ]; then
-    echo 'error: cannot find package.json'
-    exit 1
+	echo 'error: cannot find package.json'
+	exit 1
 fi
 
 name="$(jq --raw-output '.name' package.json)"
diff --git a/bin/expand-windows-path b/bin/expand-windows-path
--- a/bin/expand-windows-path
+++ b/bin/expand-windows-path
@@ -12,20 +12,20 @@ Flags:
     -h, --help  show this help text"
 
 if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
-  echo "$usage"
-  exit 0
+	echo "$usage"
+	exit 0
 fi
 
 path="${1:-}"
 if [ -z "$path" ]; then
-  echo 'error: must pass a path'
-  exit 1
+	echo 'error: must pass a path'
+	exit 1
 fi
 
-pushd /c > /dev/null
+pushd /c >/dev/null
 
 # https://superuser.com/a/1391349/201849
 cmd.exe /C "echo | set /p _=$1"
 echo
 
-popd > /dev/null
+popd >/dev/null
diff --git a/bin/gen-npm-readme b/bin/gen-npm-readme
--- a/bin/gen-npm-readme
+++ b/bin/gen-npm-readme
@@ -3,8 +3,8 @@
 set -euo pipefail
 
 if ! [ -f package.json ]; then
-    echo 'error: cannot find package.json'
-    exit 1
+	echo 'error: cannot find package.json'
+	exit 1
 fi
 
 name
@@ -14,4 +14,4 @@ description="$(jq --raw-output '.description' package.json)"
 
 echo "# $name
 
-$description" > README.md
+$description" >README.md
diff --git a/bin/get-default-branch b/bin/get-default-branch
--- a/bin/get-default-branch
+++ b/bin/get-default-branch
@@ -7,10 +7,10 @@ set -euo pipefail
 remote=${1:-origin}
 
 # If default branch ref is not present, try to update it
-if ! git symbolic-ref --quiet "refs/remotes/$remote/HEAD" &> /dev/null && \
-  ! git remote set-head "$remote" --auto &> /dev/null; then
-  echo 'failed to get default branch from remote'
-  return 1
+if ! git symbolic-ref --quiet "refs/remotes/$remote/HEAD" &>/dev/null &&
+	! git remote set-head "$remote" --auto &>/dev/null; then
+	echo 'failed to get default branch from remote'
+	return 1
 fi
 
 default_branch="$(git symbolic-ref "refs/remotes/$remote/HEAD")"
diff --git a/bin/get-node-versions b/bin/get-node-versions
--- a/bin/get-node-versions
+++ b/bin/get-node-versions
@@ -16,10 +16,10 @@ latest=1
 json=1
 
 set +e
-getopt --test > /dev/null
+getopt --test >/dev/null
 if [ $? -ne 4 ]; then
-  echo 'error: enhanced getopt is not installed' >&2
-  exit 1
+	echo 'error: enhanced getopt is not installed' >&2
+	exit 1
 fi
 set -e
 
@@ -28,45 +28,45 @@ eval set -- "$opts"
 unset opts
 
 while true; do
-  case "$1" in
-    '-h'|'--help')
-      echo "$usage"
-      exit
-    ;;
-    '-l'|'--latest')
-      latest=0
-      shift
-      continue
-    ;;
-    '-L'|'--lts')
-      lts=0
-      shift
-      continue
-    ;;
-    '-j'|'--json')
-      json=0
-      shift
-      continue
-    ;;
-    '--')
-      shift
-      break
-    ;;
-    *)
-      echo 'error: failed to parse arguments' >&2
-      exit 1
-    ;;
-  esac
+	case "$1" in
+	'-h' | '--help')
+		echo "$usage"
+		exit
+		;;
+	'-l' | '--latest')
+		latest=0
+		shift
+		continue
+		;;
+	'-L' | '--lts')
+		lts=0
+		shift
+		continue
+		;;
+	'-j' | '--json')
+		json=0
+		shift
+		continue
+		;;
+	'--')
+		shift
+		break
+		;;
+	*)
+		echo 'error: failed to parse arguments' >&2
+		exit 1
+		;;
+	esac
 done
 
 if ! check-installed jq https://stedolan.github.io/jq/; then
-  exit 1
+	exit 1
 fi
 
 node_versions_url='https://nodejs.org/dist/index.json'
 if ! versions="$(curl --silent --fail --show-error "$node_versions_url")"; then
-  echo 'error: failed to get Node versions'
-  exit 1
+	echo 'error: failed to get Node versions'
+	exit 1
 fi
 
 filter='.'
@@ -74,17 +74,16 @@ filter='.'
 filter+=' | sort_by(.date)'
 
 if [ $lts -eq 0 ]; then
-  filter+=' | map(select(.lts))'
+	filter+=' | map(select(.lts))'
 fi
 
 if [ $latest -eq 0 ]; then
-  filter+=' | sort_by(.modules, .version) | [last]'
+	filter+=' | sort_by(.modules, .version) | [last]'
 fi
 
 if [ $json -eq 0 ]; then
-  echo "$versions" | jq "$filter"
+	echo "$versions" | jq "$filter"
 else
-  filter+=' | map(.date + " | " + .version + (if .lts then " (lts)" else "" end)) | .[]'
-  echo "$versions" | jq --raw-output "$filter"
+	filter+=' | map(.date + " | " + .version + (if .lts then " (lts)" else "" end)) | .[]'
+	echo "$versions" | jq --raw-output "$filter"
 fi
-
diff --git a/bin/git-stat-all b/bin/git-stat-all
--- a/bin/git-stat-all
+++ b/bin/git-stat-all
@@ -9,74 +9,74 @@ Flags:
     -h, --help  show this help text"
 
 if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
-  echo "$usage"
-  exit 0
+	echo "$usage"
+	exit 0
 fi
 
 is-git-repository() {
-  local dir
-  dir="${1:-.}"
-  [ -d "$dir"/.git ]
+	local dir
+	dir="${1:-.}"
+	[ -d "$dir"/.git ]
 }
 
 # Print a message about unpushed commits if there are any
 # $1: directory
 print-unpushed() {
-  local d
-  d="${1:-}"
+	local d
+	d="${1:-}"
 
-  if num="$(git -C "$d" rev-list '@{upstream}..' --count 2> /dev/null)" && [ "$num" != "0" ]; then
-    if [ "$num" = "1" ]; then
-      echo "1 unpushed commit"
-    else
-      echo "$num unpushed commits"
-    fi
-  fi
+	if num="$(git -C "$d" rev-list '@{upstream}..' --count 2>/dev/null)" && [ "$num" != "0" ]; then
+		if [ "$num" = "1" ]; then
+			echo "1 unpushed commit"
+		else
+			echo "$num unpushed commits"
+		fi
+	fi
 }
 
 # Print git status for directory if it has changes
 # $1: directory
 print-status-if-dirty() {
-  local d
-  d="${1:-}"
+	local d
+	d="${1:-}"
 
-  if ! git -C "$d" diff-index --quiet --ignore-submodules=all HEAD -- || \
-     [ -n "$(git -C "$d" ls-files --exclude-standard --others)" ]; then
-    # Redirect stderr so that nothing is printed if the command fails
-    git -C "$d" -c color.ui=always status --short 2> /dev/null
-  fi
+	if ! git -C "$d" diff-index --quiet --ignore-submodules=all HEAD -- ||
+		[ -n "$(git -C "$d" ls-files --exclude-standard --others)" ]; then
+		# Redirect stderr so that nothing is printed if the command fails
+		git -C "$d" -c color.ui=always status --short 2>/dev/null
+	fi
 }
 
 # Show current state of a Git repository
 # $1: directory
 stat-repo() {
-  local bold="\\e[1m"
-  local reset="\\e[0m"
+	local bold='\e[1m'
+	local reset='\e[0m'
 
-  local d
-  d="${1:-}"
+	local d
+	d="${1:-}"
 
-  if ! is-git-repository "$d"; then
-    return 1
-  fi
+	if ! is-git-repository "$d"; then
+		return 1
+	fi
 
-  local message=''  
+	local message=''
 
-  local unpushed
-  unpushed="$(print-unpushed "$d")"
-  [ -n "$unpushed" ] && message+="\\n$unpushed"
+	local unpushed
+	unpushed="$(print-unpushed "$d")"
+	[ -n "$unpushed" ] && message+="\\n$unpushed"
 
-  local status
-  status="$(print-status-if-dirty "$d")"
-  [ -n "$status" ] && message+="\\n$status"
+	local status
+	status="$(print-status-if-dirty "$d")"
+	[ -n "$status" ] && message+="\\n$status"
 
-  if [ -n "$message" ]; then
-    # Print all at once to prevent interleaving when run in parallel
-    echo -e "$bold$d$reset$message"
-  fi
+	if [ -n "$message" ]; then
+		# Print all at once to prevent interleaving when run in parallel
+		echo -e "$bold$d$reset$message"
+	fi
 }
 
 for d in */; do
-  stat-repo "$d" &
+	stat-repo "$d" &
 done
 wait
diff --git a/bin/i b/bin/i
--- a/bin/i
+++ b/bin/i
@@ -20,10 +20,10 @@ Examples:
     i afk lunch"
 
 set +e
-getopt --test > /dev/null
+getopt --test >/dev/null
 if [ $? -ne 4 ]; then
-  echo 'error: enhanced getopt is not installed' >&2
-  exit 1
+	echo 'error: enhanced getopt is not installed' >&2
+	exit 1
 fi
 set -e
 
@@ -32,121 +32,121 @@ eval set -- "$opts"
 unset opts
 
 while true; do
-  case "$1" in
-    '-h'|'--help')
-      echo "$usage"
-      exit
-    ;;
-    '--')
-      shift
-      break
-    ;;
-    *)
-      echo 'error: failed to parse arguments' >&2
-      exit 1
-    ;;
-  esac
+	case "$1" in
+	'-h' | '--help')
+		echo "$usage"
+		exit
+		;;
+	'--')
+		shift
+		break
+		;;
+	*)
+		echo 'error: failed to parse arguments' >&2
+		exit 1
+		;;
+	esac
 done
 
 if ! check-installed jq https://stedolan.github.io/jq/ || ! check-installed slack https://github.com/rockymadden/slack-cli; then
-  exit 1
+	exit 1
 fi
 
 # $1: duration in minutes
 focus() {
-  local duration="${1:-}"
-  if [ -z "$duration" ]; then
-    duration='30'
-  fi
+	local duration="${1:-}"
+	if [ -z "$duration" ]; then
+		duration='30'
+	fi
 
-  local end_time
-  if end_time="$(date '+%-I:%M %p' --date "$duration min")"; then
-    echo "focusing until $end_time ($duration minutes)"
-  else
-    echo 'failed to calculate Slack status expiration end time'
-  fi
+	local end_time
+	if end_time="$(date '+%-I:%M %p' --date "$duration min")"; then
+		echo "focusing until $end_time ($duration minutes)"
+	else
+		echo 'failed to calculate Slack status expiration end time'
+	fi
 
-  if ! slack snooze start "$duration" > /dev/null; then
-    echo 'failed to snooze Slack notifications'
-  fi
+	if ! slack snooze start "$duration" >/dev/null; then
+		echo 'failed to snooze Slack notifications'
+	fi
 
-  if ! slack status edit 'focusing' ':thought_balloon:' > /dev/null; then
-    echo 'failed to set Slack status'
-  fi
+	if ! slack status edit 'focusing' ':thought_balloon:' >/dev/null; then
+		echo 'failed to set Slack status'
+	fi
 
-  if [ -n "${SLACK_CLI_TOKEN:-}" ]; then
-    local duration_ms
-    # Subtract one minute to account for difference between snooze and status time handling
-    if ! duration_ms=$(date +%s --date "$duration min - 1 min"); then
-      echo 'failed to calculate Slack status expiration duration'
-    elif ! curl -s -X POST https://slack.com/api/users.profile.set \
-      --data-urlencode "profile={\"status_expiration\": $duration_ms}" \
-      --data-urlencode "token=${SLACK_CLI_TOKEN}" > /dev/null; then
-      echo 'failed to set Slack status expiration'
-    fi
-  else
-    echo 'error: cannot set Slack status expiration because SLACK_CLI_TOKEN is not set'
-  fi
+	if [ -n "${SLACK_CLI_TOKEN:-}" ]; then
+		local duration_ms
+		# Subtract one minute to account for difference between snooze and status time handling
+		if ! duration_ms=$(date +%s --date "$duration min - 1 min"); then
+			echo 'failed to calculate Slack status expiration duration'
+		elif ! curl -s -X POST https://slack.com/api/users.profile.set \
+			--data-urlencode "profile={\"status_expiration\": $duration_ms}" \
+			--data-urlencode "token=${SLACK_CLI_TOKEN}" >/dev/null; then
+			echo 'failed to set Slack status expiration'
+		fi
+	else
+		echo 'error: cannot set Slack status expiration because SLACK_CLI_TOKEN is not set'
+	fi
 }
 
 unfocus() {
-  echo 'ending focus period'
-  if ! slack snooze end > /dev/null; then
-    echo 'failed to end Slack snooze'
-  fi
+	echo 'ending focus period'
+	if ! slack snooze end >/dev/null; then
+		echo 'failed to end Slack snooze'
+	fi
 
-  if ! slack status clear > /dev/null; then
-    echo 'failed to clear Slack status'
-  fi
+	if ! slack status clear >/dev/null; then
+		echo 'failed to clear Slack status'
+	fi
 }
 
 afk() {
-  local type="${1:-}"
-  if [ "$type" = 'lunch' ]; then
-    status='lunch'
-    emoji='knife_fork_plate'
-  elif [ "$type" = 'out' ]; then
-    status='out of office'
-    emoji='spiral_calendar_pad'
-  elif [ "$type" = 'tea' ]; then
-    status='away from keyboard (making tea)'
-    emoji='tea'
-  else
-    status='away from keyboard'
-    emoji='timer_clock'
-  fi
+	local type="${1:-}"
+	if [ "$type" = 'lunch' ]; then
+		status='lunch'
+		emoji='knife_fork_plate'
+	elif [ "$type" = 'out' ]; then
+		status='out of office'
+		emoji='spiral_calendar_pad'
+	elif [ "$type" = 'tea' ]; then
+		status='away from keyboard (making tea)'
+		emoji='tea'
+	else
+		status='away from keyboard'
+		emoji='timer_clock'
+	fi
 
-  echo 'going away from keyboard'
-  if ! slack status edit "$status" ":${emoji}:" > /dev/null; then
-    echo 'failed to set Slack status'
-  fi
+	echo 'going away from keyboard'
+	if ! slack status edit "$status" ":${emoji}:" >/dev/null; then
+		echo 'failed to set Slack status'
+	fi
 
-  if ! slack presence away > /dev/null; then
-    echo 'failed to set Slack presence'
-  fi
+	if ! slack presence away >/dev/null; then
+		echo 'failed to set Slack presence'
+	fi
 }
 
 unafk() {
-  echo 'coming back to keyboard'
-  if ! slack status clear > /dev/null; then
-    echo 'failed to clear Slack status'
-  fi
+	echo 'coming back to keyboard'
+	if ! slack status clear >/dev/null; then
+		echo 'failed to clear Slack status'
+	fi
 
-  if ! slack presence active > /dev/null; then
-    echo 'failed to set Slack presence'
-  fi
+	if ! slack presence active >/dev/null; then
+		echo 'failed to set Slack presence'
+	fi
 }
 
 if [ "$1" = 'focus' ]; then
-  shift
-  focus "$@"
+	shift
+	focus "$@"
 elif [ "$1" = 'unfocus' ]; then
-  shift
-  unfocus "$@"
+	shift
+	unfocus "$@"
 elif [ "$1" = 'afk' ]; then
-  shift
-  afk "$@"
+	shift
+	afk "$@"
 elif [ "$1" = 'unafk' ]; then
-  shift
-  unafk "$@"
+	shift
+	unafk "$@"
 fi
diff --git a/bin/log-branch-commits b/bin/log-branch-commits
--- a/bin/log-branch-commits
+++ b/bin/log-branch-commits
@@ -2,7 +2,8 @@
 
 set -euo pipefail
 
-readonly usage="$(cat <<EOF
+readonly usage="$(
+	cat <<EOF
 Usage: $(basename "$0") [-h|--help] [--pr] [-r|--remote] [branch]
 Log all commits on the current branch that are not on another branch.
 
@@ -19,10 +20,10 @@ EOF
 pull_request=1
 
 set +e
-getopt --test > /dev/null
+getopt --test >/dev/null
 if [ $? -ne 4 ]; then
-  echo 'error: enhanced getopt is not installed' >&2
-  exit 1
+	echo 'error: enhanced getopt is not installed' >&2
+	exit 1
 fi
 set -e
 
@@ -33,52 +34,52 @@ unset opts
 remote='origin'
 
 while true; do
-  case "$1" in
-    '-h'|'--help')
-      echo "$usage"
-      exit
-    ;;
-    '--pr')
-      pull_request=0
-      shift
-      continue
-    ;;
-    '-r'|'--remote')
-      remote="$2"
-      shift 2
-      continue
-    ;;
-    '--')
-      shift
-      break
-    ;;
-    *)
-      echo 'error: failed to parse arguments' >&2
-      exit 1
-    ;;
-  esac
+	case "$1" in
+	'-h' | '--help')
+		echo "$usage"
+		exit
+		;;
+	'--pr')
+		pull_request=0
+		shift
+		continue
+		;;
+	'-r' | '--remote')
+		remote="$2"
+		shift 2
+		continue
+		;;
+	'--')
+		shift
+		break
+		;;
+	*)
+		echo 'error: failed to parse arguments' >&2
+		exit 1
+		;;
+	esac
 done
 
 if ! default_branch="$(get-default-branch)"; then
-  echo 'error: could not get default branch'
-  return 1
+	echo 'error: could not get default branch'
+	return 1
 fi
 
 branch="${1:-$default_branch}"
 
 git_log() {
-  git log "$remote"/"$branch".. "$@" --
+	git log "$remote"/"$branch".. "$@" --
 }
 
 if [ $pull_request -eq 0 ]; then
-  # 1. Format commits as Markdown list items:
-  # - <subject>
-  #   <body indented by two spaces>
-  #
-  # 2. Replace `# ` with `- `, preserving any indentation, to change comments into list items
-  # 3. Replace tabs with four spaces so that indentation works correctly in Markdown
-  git_log '--pretty=format:- %s%w(0,2,2)%+b' | \
-    sed -E -e 's/#(\s+)/\1- /g' -e 's/\t/    /g'
+	# 1. Format commits as Markdown list items:
+	# - <subject>
+	#   <body indented by two spaces>
+	#
+	# 2. Replace `# ` with `- `, preserving any indentation, to change comments into list items
+	# 3. Replace tabs with four spaces so that indentation works correctly in Markdown
+	git_log '--pretty=format:- %s%w(0,2,2)%+b' |
+		sed -E -e 's/#(\s+)/\1- /g' -e 's/\t/    /g'
 else
-  git_log --oneline --pretty=who-when-what
+	git_log --oneline --pretty=who-when-what
 fi
diff --git a/bin/merge-pr b/bin/merge-pr
--- a/bin/merge-pr
+++ b/bin/merge-pr
@@ -12,10 +12,10 @@ Flags:
 force=1
 
 set +e
-getopt --test > /dev/null
+getopt --test >/dev/null
 if [ $? -ne 4 ]; then
-  echo 'error: enhanced getopt is not installed' >&2
-  exit 1
+	echo 'error: enhanced getopt is not installed' >&2
+	exit 1
 fi
 set -e
 
@@ -24,50 +24,50 @@ eval set -- "$opts"
 unset opts
 
 while true; do
-  case "$1" in
-    '-h'|'--help')
-      echo "$usage"
-      exit
-    ;;
-    '-f'|'--force')
-      force=0
-      shift
-      continue
-    ;;
-    '--')
-      shift
-      break
-    ;;
-    *)
-      echo 'error: failed to parse arguments' >&2
-      exit 1
-    ;;
-  esac
+	case "$1" in
+	'-h' | '--help')
+		echo "$usage"
+		exit
+		;;
+	'-f' | '--force')
+		force=0
+		shift
+		continue
+		;;
+	'--')
+		shift
+		break
+		;;
+	*)
+		echo 'error: failed to parse arguments' >&2
+		exit 1
+		;;
+	esac
 done
 
 if ! check-installed hub https://hub.github.com/; then
-  return 1
+	return 1
 fi
 
 errlog() {
-	>&2 echo "$@"
+	echo >&2 "$@"
 }
 
 parse_remote() {
-  remote='origin'
-  if ! remote_url="$(git remote get-url "$remote")"; then
-    errlog "error: failed to get remote URL from remote '$remote'"
-    return 1
-  fi
+	remote='origin'
+	if ! remote_url="$(git remote get-url "$remote")"; then
+		errlog "error: failed to get remote URL from remote '$remote'"
+		return 1
+	fi
 
-  regex=".+[:\/](.+\/.+)\.git"
-  if [[ "$remote_url" =~ $regex ]]; then
-    echo "${BASH_REMATCH[1]}"
-    return
-  fi
+	regex=".+[:\/](.+\/.+)\.git"
+	if [[ $remote_url =~ $regex ]]; then
+		echo "${BASH_REMATCH[1]}"
+		return
+	fi
 
-  errlog "error: failed to parse remote URL '$remote_url'"
-  return 1
+	errlog "error: failed to parse remote URL '$remote_url'"
+	return 1
 }
 
 current_branch="$(git rev-parse --abbrev-ref HEAD)"
@@ -77,16 +77,16 @@ default_branch="$(get-default-branch origin)"
 # - Set delimiter (`-d`) to `%` instead of the default, which is newline
 # - Format is title, newline, body, newline, URL, percent sign
 # shellcheck disable=SC2162
-IFS=$'\n' read -d '%' title base_branch pull_request_url < <( hub pr show --head "$current_branch" --format '%t%n%B%n%U%%')
+IFS=$'\n' read -d '%' title base_branch pull_request_url < <(hub pr show --head "$current_branch" --format '%t%n%B%n%U%%')
 
 if [ "$current_branch" = "$default_branch" ]; then
-  errlog "error: current branch is default branch, please run again from a different branch"
-  exit 1
+	errlog "error: current branch is default branch, please run again from a different branch"
+	exit 1
 fi
 
 branch="$default_branch"
 if [ -n "$base_branch" ]; then
-  branch="$base_branch"
+	branch="$base_branch"
 fi
 
 message_args=()
@@ -95,24 +95,24 @@ if [ -n "$title" ]; then
 	message="$title
 
 $pull_request_url"
-  message_args=('--message' "$message")
+	message_args=('--message' "$message")
 fi
 
 if [ $force -eq 0 ]; then
-  if ! owner_slash_repository="$(parse_remote)"; then
-    errlog 'error: failed to extract owner/repository from Git remotes'
-  fi
+	if ! owner_slash_repository="$(parse_remote)"; then
+		errlog 'error: failed to extract owner/repository from Git remotes'
+	fi
 fi
 
 if [ $force -eq 0 ]; then
 	echo 'disabling branch protection...'
-  if ! hub api -X DELETE /repos/"$owner_slash_repository"/branches/"$base_branch"/protection/enforce_admins > /dev/null; then
-    errlog "warning: failed to disable branch protection on '$owner_slash_repository' branch '$base_branch'"
-  fi
+	if ! hub api -X DELETE /repos/"$owner_slash_repository"/branches/"$base_branch"/protection/enforce_admins >/dev/null; then
+		errlog "warning: failed to disable branch protection on '$owner_slash_repository' branch '$base_branch'"
+	fi
 
 	enable_branch_protection() {
 		echo 're-enabling branch protection...'
-		if ! hub api -X POST /repos/"$owner_slash_repository"/branches/"$base_branch"/protection/enforce_admins > /dev/null; then
+		if ! hub api -X POST /repos/"$owner_slash_repository"/branches/"$base_branch"/protection/enforce_admins >/dev/null; then
 			errlog "warning: failed to enable branch protection on '$owner_slash_repository' branch '$base_branch'"
 		fi
 	}
@@ -159,11 +159,11 @@ fi
 
 # Only delete local branch if all operations succeed
 if ! git branch --delete "$current_branch"; then
-  errlog "warning: failed to delete '$current_branch' locally"
+	errlog "warning: failed to delete '$current_branch' locally"
 fi
 
 # If remote branch deletion fails and branch still exists on remote, log a warning
-if ! git push origin --delete "$current_branch" &> /dev/null && \
-    git ls-remote --exit-code --quiet --heads origin "$current_branch" > /dev/null; then
-  echo "warning: failed to delete '$current_branch' on the remote"
+if ! git push origin --delete "$current_branch" &>/dev/null &&
+	git ls-remote --exit-code --quiet --heads origin "$current_branch" >/dev/null; then
+	echo "warning: failed to delete '$current_branch' on the remote"
 fi
diff --git a/bin/rgm b/bin/rgm
--- a/bin/rgm
+++ b/bin/rgm
@@ -9,31 +9,31 @@ Flags:
     -h, --help  show this help text"
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-    echo "$usage"
-    exit 0
+	echo "$usage"
+	exit 0
 fi
 
 get-ripgrep-match() {
-    if (( $# < 2 )); then
-        echo "error: must provide at least two arguments"
-        return 1
-    fi
+	if (($# < 2)); then
+		echo "error: must provide at least two arguments"
+		return 1
+	fi
 
-    local index
-    index="$1"
-    shift
+	local index
+	index="$1"
+	shift
 
-    if ! [[ "$index" =~ ^[0-9]+$ ]]; then
-      echo "error: first argument must be a number"
-      return 1
-    fi
+	if ! [[ $index =~ ^[0-9]+$ ]]; then
+		echo "error: first argument must be a number"
+		return 1
+	fi
 
-    if ! [ "$index" -gt 0 ]; then
-      echo "error: index must be greater than zero"
-      return 1
-    fi
+	if ! [ "$index" -gt 0 ]; then
+		echo "error: index must be greater than zero"
+		return 1
+	fi
 
-    rg --files-with-matches "$@" | sed "${index}q;d"
+	rg --files-with-matches "$@" | sed "${index}q;d"
 }
 
 get-ripgrep-match "$@"
diff --git a/bin/unlock-keys b/bin/unlock-keys
--- a/bin/unlock-keys
+++ b/bin/unlock-keys
@@ -2,7 +2,8 @@
 
 set -euo pipefail
 
-readonly usage="$(cat <<EOF
+readonly usage="$(
+	cat <<EOF
 Usage: $(basename "$0") [-h|--help]
 Unlock SSH and GPG keys for the duration of the session.
 
@@ -18,34 +19,34 @@ EOF
 )"
 
 if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
-  echo "$usage"
-  exit 0
+	echo "$usage"
+	exit 0
 fi
 
-if ! command -v lpass > /dev/null; then
-  echo 'error: lpass must be installed'
-  exit 1
+if ! command -v lpass >/dev/null; then
+	echo 'error: lpass must be installed'
+	exit 1
 fi
 
 if ! lpass status --quiet; then
-  echo "log in to LastPass with 'lpass login' then run this script again"
-  exit 1
+	echo "log in to LastPass with 'lpass login' then run this script again"
+	exit 1
 fi
 
-if ! command -v expect > /dev/null; then
-  echo 'error: expect must be installed'
-  exit 1
+if ! command -v expect >/dev/null; then
+	echo 'error: expect must be installed'
+	exit 1
 fi
 
 echo 'unlocking SSH key...'
 
 # Retrieve field "Passphrase" from a note in the group "ssh" named exactly the hostname of this computer
 if ! ssh_passphrase="$(lpass show --basic-regexp "ssh/$(hostname)" --field 'Passphrase')"; then
-  echo 'error: failed to get SSH key passphrase from LastPass'
-  exit 1
+	echo 'error: failed to get SSH key passphrase from LastPass'
+	exit 1
 fi
 
-expect > /dev/null << EOF
+expect >/dev/null <<EOF
   spawn ssh-add
   expect "Enter passphrase"
   send "$ssh_passphrase\r"
@@ -53,20 +54,20 @@ expect > /dev/null << EOF
 EOF
 
 if ! gpg_usernames="$(gpg --list-keys --with-colons | awk --field-separator : '/uid/ {print $10}')"; then
-  echo 'error: failed to get usernames of local GPG keys'
-  exit 1
+	echo 'error: failed to get usernames of local GPG keys'
+	exit 1
 fi
 
-mapfile -t gpg_keys < <( echo "$gpg_usernames" )
+mapfile -t gpg_keys < <(echo "$gpg_usernames")
 
 for user in "${gpg_keys[@]}"; do
-  echo "unlocking GPG key for user '$user'..."
+	echo "unlocking GPG key for user '$user'..."
 
-  # Retrieve field "Passphrase" from a note in the group "gpg" named exactly the username of this key
-  if ! gpg_passphrase="$(lpass show --basic-regexp "gpg/$user" --field 'Passphrase')"; then
-    echo "error: failed to get GPG key passphrase for user '$user'"
-    continue
-  fi
+	# Retrieve field "Passphrase" from a note in the group "gpg" named exactly the username of this key
+	if ! gpg_passphrase="$(lpass show --basic-regexp "gpg/$user" --field 'Passphrase')"; then
+		echo "error: failed to get GPG key passphrase for user '$user'"
+		continue
+	fi
 
-  echo | gpg --local-user "$user" --batch --pinentry-mode loopback --passphrase-file <( echo "$gpg_passphrase" ) --sign >/dev/null
+	echo | gpg --local-user "$user" --batch --pinentry-mode loopback --passphrase-file <(echo "$gpg_passphrase") --sign >/dev/null
 done
diff --git a/bin/watch-ci b/bin/watch-ci
--- a/bin/watch-ci
+++ b/bin/watch-ci
@@ -5,14 +5,14 @@ set -euo pipefail
 # Print CI status, filtering user tracking URL query parameters.
 # $1: commit SHA to print status for
 print_ci_status() {
-  set +e
-  hub ci-status --verbose --color "$1" | sed -E 's/\?utm.+$//'
-  set -e
+	set +e
+	hub ci-status --verbose --color "$1" | sed -E 's/\?utm.+$//'
+	set -e
 }
 
 # Watch continuous integration for the current HEAD commit, printing out status as it changes
 if ! check-installed hub https://hub.github.com/; then
-  exit 1
+	exit 1
 fi
 
 # Cache head commit to avoid breaking when the user makes a new commit on the branch locally
@@ -20,13 +20,13 @@ head="$(git rev-parse HEAD)"
 
 # hub ci-status exits non-zero when CI fails
 set +e
-hub ci-status "$head" > /dev/null
+hub ci-status "$head" >/dev/null
 ci_status_exit_code=$?
 set -e
 
 if [ $ci_status_exit_code = 3 ]; then
-  echo "could not find CI status"
-  exit 1
+	echo "could not find CI status"
+	exit 1
 fi
 
 ci_status_all="$(print_ci_status "$head")"
@@ -34,32 +34,32 @@ echo -e "$ci_status_all"
 
 # Check CI status every five seconds, terminate loop if it is no longer pending
 while [ $ci_status_exit_code = 2 ]; do
-  sleep 5
+	sleep 5
 
-  # Check if the status of individual checks has changed, only log them if it has
-  ci_status_all_new="$(print_ci_status "$head")"
-  if [ "$ci_status_all" != "$ci_status_all_new" ]; then
-    ci_status_all="$ci_status_all_new"
-    tput clear
-    echo -e "$ci_status_all"
-  fi
+	# Check if the status of individual checks has changed, only log them if it has
+	ci_status_all_new="$(print_ci_status "$head")"
+	if [ "$ci_status_all" != "$ci_status_all_new" ]; then
+		ci_status_all="$ci_status_all_new"
+		tput clear
+		echo -e "$ci_status_all"
+	fi
 
-  set +e
-  hub ci-status "$head" > /dev/null
-  ci_status_exit_code=$?
-  set -e
+	set +e
+	hub ci-status "$head" >/dev/null
+	ci_status_exit_code=$?
+	set -e
 done
 
 project="$(basename "$(pwd)")"
 
 if [ $ci_status_exit_code = 0 ]; then
-  message="CI for $project succeeded."
+	message="CI for $project succeeded."
 elif [ $ci_status_exit_code = 1 ]; then
-  message="CI for $project failed."
+	message="CI for $project failed."
 else
-  message="Something unexpected happened in CI for $project."
+	message="Something unexpected happened in CI for $project."
 fi
 
 if is-macos; then
-  osascript -e "display notification \"$message\" with title \"watch-ci\""
+	osascript -e "display notification \"$message\" with title \"watch-ci\""
 fi
diff --git a/lib/helpers b/lib/helpers
--- a/lib/helpers
+++ b/lib/helpers
@@ -20,18 +20,39 @@ message() {
 	OFF=0
 	# More color codes: https://misc.flogisoft.com/bash/tip_colors_and_formatting
 	case $1 in
-		off)     COLOR=0; shift ;;
-		red)     COLOR=31; shift ;;
-		green)   COLOR=32; shift ;;
-		yellow)  COLOR=33; shift ;;
-		blue)    COLOR=34; shift ;;
-		magenta) COLOR=35; shift ;;
-		cyan)    COLOR=36; shift ;;
+	off)
+		COLOR=0
+		shift
+		;;
+	red)
+		COLOR=31
+		shift
+		;;
+	green)
+		COLOR=32
+		shift
+		;;
+	yellow)
+		COLOR=33
+		shift
+		;;
+	blue)
+		COLOR=34
+		shift
+		;;
+	magenta)
+		COLOR=35
+		shift
+		;;
+	cyan)
+		COLOR=36
+		shift
+		;;
 	esac
 
 	# Get template from $1 if it is set, default to empty otherwise
 	TEMPLATE=
-	if [[ -n "$1" ]]; then
+	if [[ -n $1 ]]; then
 		TEMPLATE=${1:-}
 		shift
 	fi
@@ -72,15 +93,15 @@ confirm() {
 	# Whether or not to skip prompt
 	# Use value of SHOULD_CONFIRM; if not set, default to 1 (skip prompt)
 	SHOULD_PROMPT=${SHOULD_CONFIRM:-1}
-	if [[ "$SHOULD_PROMPT" = 1 ]]; then
-			return 0 # automatic yes
+	if [[ $SHOULD_PROMPT == 1 ]]; then
+		return 0 # automatic yes
 	fi
 
 	MESSAGE=${1:-"Proceed?"}
 	read -p "$MESSAGE (y/n) " -n 1 -r
 	message
 	[[ $REPLY =~ ^[Yy]$ ]] # REPLY is automatically set to the result of `read`
-	return $? # result of previous line, either 0 (yes) or 1 (no)
+	return $?              # result of previous line, either 0 (yes) or 1 (no)
 }
 
 # cURL wrapper with common default options
@@ -92,18 +113,18 @@ _curl() {
 # $1: repository URL in format: [owner]/[repo name]
 # $2: pattern to match
 get_release_url() {
-		repository="${1:-}"
-		pattern="${2:-}"
-    # Check if jq is available for JSON parsing
-    if ! command -v jq > /dev/null; then
-        warn "could not get release url for $1 because jq is not installed"
-        return 100
-    fi
+	repository="${1:-}"
+	pattern="${2:-}"
+	# Check if jq is available for JSON parsing
+	if ! command -v jq >/dev/null; then
+		warn "could not get release url for $1 because jq is not installed"
+		return 100
+	fi
 
-    # Get list of releases
-    curl -s "https://api.github.com/repos/${repository}/releases/latest" | \
-        jq --arg pattern "$pattern" --raw-output \
-					'.assets | map(.browser_download_url | select(contains($pattern))) | first'
+	# Get list of releases
+	curl -s "https://api.github.com/repos/${repository}/releases/latest" |
+		jq --arg pattern "$pattern" --raw-output \
+			'.assets | map(.browser_download_url | select(contains($pattern))) | first'
 }
 
 # Install a binary to ~/.local/bin from a URL
@@ -125,12 +146,12 @@ install_binary_from_url() {
 # If any arguments are provided, they will be passed to sudo
 # If no arguments are provided, update the user's cached credentials and extend the sudo timeout for five minutes
 request-sudo() {
-    SUDO_PROMPT="Enter the system password for user %p: "
-    if [[ $# -eq 0 ]]; then
-        sudo --validate --prompt "$SUDO_PROMPT"
-    else
-        sudo --prompt "$SUDO_PROMPT" "$@"
-    fi
+	SUDO_PROMPT="Enter the system password for user %p: "
+	if [[ $# -eq 0 ]]; then
+		sudo --validate --prompt "$SUDO_PROMPT"
+	else
+		sudo --prompt "$SUDO_PROMPT" "$@"
+	fi
 }
 
 xdg_config() {
diff --git a/lib/linux b/lib/linux
--- a/lib/linux
+++ b/lib/linux
@@ -11,11 +11,11 @@ request-sudo
 message "  %s" "setting up Linux..."
 
 message "    %s" "installing essential tools..."
-if command -v apt-get > /dev/null; then
-    sudo apt-get update > /dev/null
-    sudo apt-get install --yes build-essential curl file git jq > /dev/null
+if command -v apt-get >/dev/null; then
+	sudo apt-get update >/dev/null
+	sudo apt-get install --yes build-essential curl file git jq >/dev/null
 else
-    error "could not find a supported package manager; skipping install"
+	error "could not find a supported package manager; skipping install"
 fi
 message "    %s" "done installing essential tools."
 
@@ -51,7 +51,7 @@ if ! _curl "$exa_url" --output "$exa_zip_tmp"; then
 fi
 
 exa_tmp="$(mktemp -d)"
-if ! unzip "$exa_zip_tmp" 'exa-linux-x86_64' -d "$exa_tmp" > /dev/null; then
+if ! unzip "$exa_zip_tmp" 'exa-linux-x86_64' -d "$exa_tmp" >/dev/null; then
 	fatal 'failed to unzip exa'
 fi
 rm -f "$exa_zip_tmp"
@@ -74,7 +74,7 @@ if ! _curl "$scc_url" --output "$scc_zip_tmp"; then
 fi
 
 scc_tmp="$(mktemp -d)"
-if ! unzip "$scc_zip_tmp" 'scc' -d "$scc_tmp" > /dev/null; then
+if ! unzip "$scc_zip_tmp" 'scc' -d "$scc_tmp" >/dev/null; then
 	fatal 'failed to unzip scc'
 fi
 rm -f "$scc_zip_tmp"
@@ -104,7 +104,7 @@ if ! _curl "$hub_url" --output "$hub_tmp"; then
 	fatal 'failed to download Hub'
 fi
 hub_extracted_tmp="$(mktemp -d)"
-if ! tar zxvf "$hub_tmp" -C "$hub_extracted_tmp" --strip-components=1 > /dev/null; then
+if ! tar zxvf "$hub_tmp" -C "$hub_extracted_tmp" --strip-components=1 >/dev/null; then
 	fatal 'failed to extract Hub'
 fi
 rm -f "$hub_tmp"
