Remove remaining main functions from shell scripts

diff --git a/bin/create-npm-repo b/bin/create-npm-repo
--- a/bin/create-npm-repo
+++ b/bin/create-npm-repo
@@ -2,17 +2,12 @@
 
 set -euo pipefail
 
-main() {
-  if ! [ -f package.json ]; then
-     echo 'error: cannot find package.json'
-     exit 1
-  fi
+if ! [ -f package.json ]; then
+    echo 'error: cannot find package.json'
+    exit 1
+fi
 
-  local name
-  name="$(jq --raw-output '.name' package.json)"
-  local description
-  description="$(jq --raw-output '.description' package.json)"
+name="$(jq --raw-output '.name' package.json)"
+description="$(jq --raw-output '.description' package.json)"
 
-  hub create --browse --description "$description" "$name"
-}
-main "$@"
+hub create --browse --description "$description" "$name"
diff --git a/bin/gen-npm-readme b/bin/gen-npm-readme
--- a/bin/gen-npm-readme
+++ b/bin/gen-npm-readme
@@ -2,19 +2,16 @@
 
 set -euo pipefail
 
-main() {
-  if ! [ -f package.json ]; then
-     echo 'error: cannot find package.json'
-     exit 1
-  fi
+if ! [ -f package.json ]; then
+    echo 'error: cannot find package.json'
+    exit 1
+fi
 
-  local name
-  name="$(jq --raw-output '.name' package.json)"
-  local description
-  description="$(jq --raw-output '.description' package.json)"
+name
+name="$(jq --raw-output '.name' package.json)"
+description
+description="$(jq --raw-output '.description' package.json)"
 
-  echo "# $name
+echo "# $name
 
 $description" > README.md
-}
-main "$@"
diff --git a/bin/get-default-branch b/bin/get-default-branch
--- a/bin/get-default-branch
+++ b/bin/get-default-branch
@@ -4,17 +4,14 @@ set -euo pipefail
 
 # Get the name of the default branch for a given remote.
 # $1: Name of a remote (defaults to origin).
-main() {
-    local remote=${1:-origin}
+remote=${1:-origin}
 
-    # If default branch ref is not present, try to update it
-    if ! git symbolic-ref --quiet "refs/remotes/$remote/HEAD" &> /dev/null && \
-      ! git remote set-head "$remote" --auto &> /dev/null; then
-      echo 'failed to get default branch from remote'
-      return 1
-    fi
+# If default branch ref is not present, try to update it
+if ! git symbolic-ref --quiet "refs/remotes/$remote/HEAD" &> /dev/null && \
+  ! git remote set-head "$remote" --auto &> /dev/null; then
+  echo 'failed to get default branch from remote'
+  return 1
+fi
 
-    default_branch="$(git symbolic-ref "refs/remotes/$remote/HEAD")"
-    echo "${default_branch##"refs/remotes/$remote/"}"
-}
-main "$@"
+default_branch="$(git symbolic-ref "refs/remotes/$remote/HEAD")"
+echo "${default_branch##"refs/remotes/$remote/"}"
diff --git a/bin/remove-submodule b/bin/remove-submodule
--- a/bin/remove-submodule
+++ b/bin/remove-submodule
@@ -4,22 +4,18 @@ set -euo pipefail
 
 # Remove a Git submodule
 # $1: path to submodule
-main() {
-  local path
-  path="${1:-}"
+path="${1:-}"
 
-  if [ -z "path" ]; then
-     echo "error: must provide path to submodule"
-     return 1
-  fi
+if [ -z "path" ]; then
+    echo "error: must provide path to submodule"
+    return 1
+fi
 
-  git submodule deinit -f "$path" || true
-  rm -rf "$path"
-  rm -rf .git/modules/"$path" || true
-  git rm -rf "$path" || true
+git submodule deinit -f "$path" || true
+rm -rf "$path"
+rm -rf .git/modules/"$path" || true
+git rm -rf "$path" || true
 
-  if ! [ -s .gitmodules ]; then
-    git rm -f .gitmodules
-  fi
-}
-main "$@"
+if ! [ -s .gitmodules ]; then
+  git rm -f .gitmodules
+fi
diff --git a/bin/watch-ci b/bin/watch-ci
--- a/bin/watch-ci
+++ b/bin/watch-ci
@@ -11,65 +11,55 @@ print_ci_status() {
 }
 
 # Watch continuous integration for the current HEAD commit, printing out status as it changes
-main() {
-  if ! check-installed hub https://hub.github.com/; then
-    return 1
+if ! check-installed hub https://hub.github.com/; then
+  return 1
+fi
+
+# Cache head commit to avoid breaking when the user makes a new commit on the branch locally
+head="$(git rev-parse HEAD)"
+
+# hub ci-status exits non-zero when CI fails
+set +e
+hub ci-status "$head" > /dev/null
+ci_status_exit_code=$?
+set -e
+
+if [ $ci_status_exit_code = 3 ]; then
+  echo "could not find CI status"
+  return 1
+fi
+
+ci_status_all="$(print_ci_status "$head")"
+echo -e "$ci_status_all"
+
+# Check CI status every five seconds, terminate loop if it is no longer pending
+while [ $ci_status_exit_code = 2 ]; do
+  sleep 5
+
+  # Check if the status of individual checks has changed, only log them if it has
+  ci_status_all_new="$(print_ci_status "$head")"
+  if [ "$ci_status_all" != "$ci_status_all_new" ]; then
+    ci_status_all="$ci_status_all_new"
+    tput clear
+    echo -e "$ci_status_all"
   fi
 
-  local head
-  local ci_status_all
-  local ci_status_all_new
-  local ci_status_exit_code
-
-  # Cache head commit to avoid breaking when the user makes a new commit on the branch locally
-  head="$(git rev-parse HEAD)"
-
-  # hub ci-status exits non-zero when CI fails
   set +e
   hub ci-status "$head" > /dev/null
   ci_status_exit_code=$?
   set -e
+done
 
-  if [ $ci_status_exit_code = 3 ]; then
-    echo "could not find CI status"
-    return 1
-  fi
+project="$(basename "$(pwd)")"
 
-  ci_status_all="$(print_ci_status "$head")"
-  echo -e "$ci_status_all"
+if [ $ci_status_exit_code = 0 ]; then
+  message="CI for $project succeeded."
+elif [ $ci_status_exit_code = 1 ]; then
+  message="CI for $project failed."
+else
+  message="Something unexpected happened in CI for $project."
+fi
 
-  # Check CI status every five seconds, terminate loop if it is no longer pending
-  while [ $ci_status_exit_code = 2 ]; do
-    sleep 5
-
-    # Check if the status of individual checks has changed, only log them if it has
-    ci_status_all_new="$(print_ci_status "$head")"
-    if [ "$ci_status_all" != "$ci_status_all_new" ]; then
-      ci_status_all="$ci_status_all_new"
-      tput clear
-      echo -e "$ci_status_all"
-    fi
-
-    set +e
-    hub ci-status "$head" > /dev/null
-    ci_status_exit_code=$?
-    set -e
-  done
-  
-  local project
-  project="$(basename "$(pwd)")"
-
-  local message
-  if [ $ci_status_exit_code = 0 ]; then
-    message="CI for $project succeeded."
-  elif [ $ci_status_exit_code = 1 ]; then
-    message="CI for $project failed."
-  else
-    message="Something unexpected happened in CI for $project."
-  fi
-
-  if is-macos; then
-    osascript -e "display notification \"$message\" with title \"watch-ci\""
-  fi
-}
-main "$@"
+if is-macos; then
+  osascript -e "display notification \"$message\" with title \"watch-ci\""
+fi
