Add untracked files to git-stat-all output

diff --git a/bin/git-stat-all b/bin/git-stat-all
--- a/bin/git-stat-all
+++ b/bin/git-stat-all
@@ -2,6 +2,8 @@
 
 set -euo pipefail
 
+DIR="$(dirname "$(realpath "$0")")"
+
 readonly usage="Usage: $(basename "$0") [-h|--help]
 Check the Git status of all subdirectories of the current directory.
 
@@ -22,24 +24,41 @@ is-git-repository() {
 # Print git status for directory if it has changes
 # $1: directory
 print-status-if-dirty() {
+  local d
+  d="${1:-}"
+
+  if ! git -C "$d" diff-index --quiet --ignore-submodules=all HEAD -- || \
+     ! [ -z "$(git -C "$d" ls-files --exclude-standard --others)" ]; then
+    # Redirect stderr so that nothing is printed if the command fails
+    git -C "$d" -c color.ui=always status --short 2> /dev/null
+  fi
+}
+
+# Show current state of a Git repository
+# $1: directory
+stat-repo() {
   local readonly bold="\\e[1m"
   local readonly reset="\\e[0m"
 
   local d
   d="${1:-}"
 
-  if is-git-repository "$d" && ! git -C "$d" diff-index --quiet --ignore-submodules=all HEAD --; then
-    local status
-    if status="$(git -C "$d" -c color.ui=always status --short)"; then
-      # Print all at once to prevent interleaving when run in parallel
-      echo -e "$bold$d$reset\\n$status"
-    fi
+  if ! is-git-repository "$d"; then
+    return 1
+  fi
+
+  local status
+  status="$(print-status-if-dirty "$d")"
+
+  if [ -n "$status" ]; then
+    # Print all at once to prevent interleaving when run in parallel
+    echo -e "$bold$d$reset\\n$status"
   fi
 }
 
 main() {
   for d in */; do
-    print-status-if-dirty "$d" &
+    stat-repo "$d" &
   done
   wait
 }
