Use a trap to ensure branch protections are re-enabled

diff --git a/bin/merge-pr b/bin/merge-pr
--- a/bin/merge-pr
+++ b/bin/merge-pr
@@ -103,6 +103,15 @@ if [ $force -eq 0 ]; then
   if ! hub api -X DELETE /repos/"$owner_slash_repository"/branches/"$base_branch"/protection/enforce_admins > /dev/null; then
     echo "warning: failed to disable branch protection on '$owner_slash_repository' branch '$base_branch'"
   fi
+
+	enable_branch_protection() {
+		if ! hub api -X POST /repos/"$owner_slash_repository"/branches/"$base_branch"/protection/enforce_admins > /dev/null; then
+			echo "warning: failed to enable branch protection on '$owner_slash_repository' branch '$base_branch'"
+		fi
+	}
+
+	# Use a trap to ensure that this runs no matter what
+	trap enable_branch_protection EXIT
 fi
 
 # After checking out the base branch, ensure it is up to date with its remote counterpart
@@ -118,11 +127,5 @@ if git pull && \
   if ! git push origin --delete "$current_branch" &> /dev/null && \
       git ls-remote --exit-code --quiet --heads origin "$current_branch" > /dev/null; then
     echo 'warning: failed to delete remote branch'
-  fi
-fi
-
-if [ $force -eq 0 ]; then
-  if ! hub api -X POST /repos/"$owner_slash_repository"/branches/"$base_branch"/protection/enforce_admins > /dev/null; then
-    echo "warning: failed to enable branch protection on '$owner_slash_repository' branch '$base_branch'"
   fi
 fi
