Remove Hub

diff --git a/bin/watch-ci b/bin/watch-ci
--- a/bin/watch-ci
+++ b/bin/watch-ci
@@ -2,65 +2,58 @@
 
 set -euo pipefail
 
-# Print CI status, filtering user tracking URL query parameters.
-# $1: commit SHA to print status for
-print_ci_status() {
-	set +e
-	hub ci-status --verbose --color "$1" | sed -E 's/\?utm.+$//'
-	set -e
-}
-
-# Watch continuous integration for the current HEAD commit, printing out status as it changes
-if ! check-installed hub https://hub.github.com/; then
+if ! check-installed gh https://cli.github.com/; then
 	exit 1
 fi
 
 # Cache head commit to avoid breaking when the user makes a new commit on the branch locally
 head="$(git rev-parse HEAD)"
+api_url="/repos/{owner}/{repo}/commits/${head}/status"
+output_template='{{range .statuses}}{{if (eq .state "success")}}🟢{{else}}{{if (eq .state "pending")}}🟡{{else}}🔴{{end}}{{end}} {{.context}}{{"\n"}}{{end}}'
 
-# hub ci-status exits non-zero when CI fails
-set +e
-hub ci-status "$head" >/dev/null
-ci_status_exit_code=$?
-set -e
+# Do not pipe gh output to a pager
+unset PAGER
 
-if [ $ci_status_exit_code = 3 ]; then
-	echo "could not find CI status"
-	exit 1
-fi
+get_state() {
+	gh api --cache="5s" --jq='.state' "$api_url"
+}
 
-ci_status_all="$(print_ci_status "$head")"
-echo -e "$ci_status_all"
+print_status() {
+	gh api --template="$output_template" "$api_url"
+}
+
+state="$(get_state)"
+print_status
 
 # Check CI status every five seconds, terminate loop if it is no longer pending
-while [ $ci_status_exit_code = 2 ]; do
+while [ "$state" = 'pending' ]; do
 	sleep 5
-
-	# Check if the status of individual checks has changed, only log them if it has
-	ci_status_all_new="$(print_ci_status "$head")"
-	if [ "$ci_status_all" != "$ci_status_all_new" ]; then
-		ci_status_all="$ci_status_all_new"
-		tput clear
-		echo -e "$ci_status_all"
+	# Cache response so that we can immediately make the same request again with different output formatting
+	if ! state="$(get_state)"; then
+		echo 'error: failed to get commit state'
+		exit 1
 	fi
 
-	set +e
-	hub ci-status "$head" >/dev/null
-	ci_status_exit_code=$?
-	set -e
+	if ! [ "$state" = 'pending' ]; then
+		break
+	fi
+
+	tput clear
+
+	print_status
 done
 
 project="$(basename "$(pwd)")"
 
-if [ $ci_status_exit_code = 0 ]; then
+if [ "$state" = 'success' ]; then
 	message="CI for $project succeeded."
-elif [ $ci_status_exit_code = 1 ]; then
+elif [ "$state" = 'failure' ]; then
 	message="CI for $project failed."
 else
 	message="Something unexpected happened in CI for $project."
 fi
 
-if [[ $OSTYPE == darwin* ]]; then
+if [[ "$OSTYPE" == darwin* ]]; then
 	osascript -e "display notification \"$message\" with title \"watch-ci\""
 elif command -v notify-send >/dev/null; then
 	notify-send 'watch-ci' "$message"
