Move bootstrap to bin
- remove bootstrap's file extension
	The file extension was not necessary nor accurate, so it was solely
	an inconvenience.
- prepend bootstrap's name with a comma
	Based on https://rhodesmill.org/brandon/2009/commands-with-comma/.
- change bootstrap from Bash to POSIX sh
	This forces the script to use minimal features that should be
	available on every fresh system.
- verify bootstrap POSIX sh compliance in pre-commit script
- move bootstrap to `./bin`
	This helps organize the repository's files a bit more and follows
	the established pattern for general-purpose scripts.
- move the majority of bootstrap into a new `lib/main` script
	The `,bootstrap` entrypoint is a minimal POSIX-compliant shim
	that installs utilities necessary for the rest of the
	script. `lib/main` does the majority of what `bootstrap.sh` used to
	do.
- modify `helpers.sh` shebang to support `source` correctly

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -16,6 +16,11 @@ fi
 
 pushd "$(git rev-parse --show-toplevel)" >/dev/null
 
+bootstrap_path='bin/,bootstrap'
+if [[ $shell_files == *"$bootstrap_path"* ]] && ! shfmt --ln posix "$bootstrap_path" >/dev/null; then
+	echo "error: $bootstrap_path must be POSIX-compatible"
+	exit 1
+fi
 
 for file in $shell_files; do
 	# -s: simplify code
