Remove Linuxbrew
I decided to remove Linuxbrew because it does not support multi-user
systems. Replacing it was mostly done by moving package names to
`lib/apt`, but required a lot of manual installations too. Most of
these changes did not affect the macOS parts of this repository.

diff --git a/lib/apt b/lib/apt
--- a/lib/apt
+++ b/lib/apt
@@ -19,40 +19,40 @@ add_repository() {
 	echo "$2" | request-sudo tee /etc/apt/sources.list.d/"$1".list > /dev/null
 }
 
+# $1: URL
+add_key() {
+	local url="${1:-}"
+	if ! _curl "$url" | sudo apt-key add -; then
+		fatal 'failed to add key'
+	fi
+}
+
 message "setting up apt..."
 
 if ! is_repository_configured 'vscode'; then
 	message '  %s' 'adding Visual Studio Code repository...'
-	if ! curl --silent --fail --show-error https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -; then
-		fatal 'failed to add key'
-	fi
+	add_key https://packages.microsoft.com/keys/microsoft.asc
 	add_repository 'vscode' 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
 	message '  %s' 'done adding Visual Studio Code repository.'
 fi
 
 if ! is_repository_configured 'spotify'; then
 	message '  %s' 'adding Spotify repository...'
-	if ! curl --silent --fail --show-error https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add -; then
-		fatal 'failed to add key'
-	fi
+	add_key https://download.spotify.com/debian/pubkey.gpg
 	add_repository 'spotify' 'deb http://repository.spotify.com stable non-free'
 	message '  %s' 'done adding Spotify repository.'
 fi
 
 if ! is_repository_configured 'slack'; then
 	message '  %s' 'adding Slack repository...'
-	if ! curl --silent --fail --show-error --location https://packagecloud.io/slacktechnologies/slack/gpgkey | sudo apt-key add -; then
-		fatal 'failed to add key'
-	fi
+	add_key https://packagecloud.io/slacktechnologies/slack/gpgkey
 	add_repository 'slack' 'deb https://packagecloud.io/slacktechnologies/slack/ubuntu/ bionic main'
 	message '  %s' 'done adding Slack repository.'
 fi
 
 if ! is_repository_configured 'signal'; then
 	message '  %s' 'adding Signal repository...'
-	if ! curl --silent --fail --show-error --location https://updates.signal.org/desktop/apt/keys.asc | sudo apt-key add -; then
-		fatal 'failed to add key'
-	fi
+	add_key https://updates.signal.org/desktop/apt/keys.asc
 	add_repository 'signal' 'deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main'
 	message '  %s' 'done adding Signal repository.'
 fi
@@ -63,37 +63,151 @@ if ! is_repository_configured 'nextcloud'; then
 	message '  %s' 'done adding Nextcloud repository.'
 fi
 
+if ! is_repository_configured 'diff-so-fancy'; then
+	message '  %s' 'adding diff-so-fancy repository...'
+	sudo add-apt-repository --yes ppa:aos1/diff-so-fancy
+	message '  %s' 'done adding diff-so-fancy repository.'
+fi
+
+if ! is_repository_configured 'azlux'; then
+	message '  %s' 'adding broot repository...'
+	add_key https://azlux.fr/repo.gpg.key
+	add_repository 'broot' 'deb http://packages.azlux.fr/debian/ buster main'
+	message '  %s' 'done adding broot repository.'
+fi
+
 message '  %s' 'updating lists...'
 request-sudo apt-get update > /dev/null
 message '  %s' 'done updating lists.'
 
-message '  %s' 'upgrading packages...'
+message '  %s' 'upgrading package...'
 request-sudo apt-get upgrade --yes --autoremove > /dev/null
 message '  %s' 'done upgrading packages.'
 
 declare -a packages=(
-	software-properties-common
+	# system dependencies
 	apt-transport-https
+	software-properties-common
+
+	# default utilities
+	gnupg
+	rsync
+	wget
+
+	# replacements of default utilities
+	bat # Better cat
+	broot # Better tree
+	diff-so-fancy # Better Git diff viewer
+	fd-find # Better find
+	htop # Better top
+	httpie # Better curl
+	ripgrep # Better grep
+
+	# command line tools
+	expect # Scripting tool for interactive programs
+	fzf # Fuzzy finder
+	gifsicle # Gif tool
+	graphviz # Graph visualization tool
+	hugo # Static site builder
+	imagemagick
+	ipcalc # IP address calculator
+	jq # JSON processor
+	magic-wormhole # Point-to-point file sharing
+	nnn # Command-line file browser
+	p7zip
+	pandoc
+	postgresql-client # PostgreSQL CLI
+	tig # Visual Git client
+	tmux
+	tree
+	unzip
+	xclip # Clipboard CLI
 	xdg-utils
 	wpasupplicant
-	code
-	spotify-client
-	slack-desktop
-	signal-desktop
-	emacs
-	nautilus-nextcloud
+
+	# shell
+	bash
+	zsh
+	zsh-syntax-highlighting
+
+	# programming languages
+	golang
+	php
+	python3
+	ruby
+	rustc
+
+	# programming language tools
+	composer # PHP
+	go-dep # Golang
+	shellcheck # Shell script linter
+
+	# web service clients
+	hub # GitHub
+	lastpass-cli
+
+	# applications
 	chromium-browser
-	fonts-firacode
+	code
+	docker.io
+	emacs
+	firefox
 	gnome-shell-extension-impatience
+	inkscape
+	kdiff3 # Merge tool
+	keybase
+	libreoffice
+	meld # Comparison tool for version control, files, and directories
+	nautilus-nextcloud
+	signal-desktop
+	slack-desktop
+	spotify-client
+	steam
+	thunderbird
+	vino # GNOME VNC server
+
+	# fonts
+	fonts-firacode
 )
 
 message '  %s' 'installing packages...'
 sudo apt-get install --yes "${packages[@]}"
 message '  %s' 'done installing packages.'
 
+# TODO delineate Snap from Apt
+message '  %s' 'installing Authy...'
+sudo snap install authy --beta
+message '  %s' 'done installing Authy.'
+
+message '  %s' 'installing yq...'
+sudo snap install yq
+message '  %s' 'done installing yq.'
+
+message '  %s' 'installing ffsend...'
+sudo snap install ffsend
+message '  %s' 'done installing ffsend.'
+
+message '  %s' 'installing GitHub CLI...'
+if ! github_cli_url="$(get_release_url 'cli/cli' 'linux_amd64.deb')"; then
+	fatal 'failed to get GitHub CLI release URL'
+fi
+github_cli_tmp="$(mktemp --suffix .deb)"
+if ! _curl "$github_cli_url" --output "$github_cli_tmp"; then
+	fatal 'failed to download GitHub CLI'
+fi
+if ! request-sudo apt-get install "$github_cli_tmp"; then
+	fatal 'failed to install GitHub CLI'
+fi
+rm -f "$github_cli_tmp"
+message '  %s' 'done installing GitHub CLI.'
+
+message '  %s' 'linking batcat to bat...'
+ln -sf /usr/bin/batcat "$HOME"/.local/bin/bat
+message '  %s' 'done linking batcat to bat.'
+
 message '  %s' 'installing Keybase...'
 readonly keybase_deb_tmp="$(mktemp --suffix=.deb)"
-if ! curl --silent --fail --show-error https://prerelease.keybase.io/keybase_amd64.deb --output "$keybase_deb_tmp"; then
+if ! _curl https://prerelease.keybase.io/keybase_amd64.deb --output "$keybase_deb_tmp"; then
 	fatal 'failed to download Keybase'
 fi
 if ! sudo apt-get install --yes "$keybase_deb_tmp" > /dev/null; then
diff --git a/lib/helpers b/lib/helpers
--- a/lib/helpers
+++ b/lib/helpers
@@ -83,19 +83,39 @@ confirm() {
 	return $? # result of previous line, either 0 (yes) or 1 (no)
 }
 
+# cURL wrapper with common default options
+_curl() {
+	curl --silent --fail --show-error --location "$@"
+}
+
 # Get the GitHub release URL matching a given pattern
 # $1: repository URL in format: [owner]/[repo name]
 # $2: pattern to match
-get-release-url() {
+get_release_url() {
     # Check if jq is available for JSON parsing
-    if [[ -z "$(command -v jq)" ]]; then
+    if ! command -v jq > /dev/null; then
         warn "could not get release url for $1 because jq is not installed"
         return 100
     fi
 
     # Get list of releases
     curl -s "https://api.github.com/repos/$1/releases/latest" | \
-        jq --raw-output ".assets[] | .browser_download_url | select(endswith(\"$2\"))"
+        jq --raw-output ".assets[] | .browser_download_url | select(contains(\"$2\"))"
+}
+
+# Install a binary to ~/.local/bin from a URL
+# $1: binary name
+# $2: URL
+install_binary_from_url() {
+	local name="${1:-}"
+	local url="${2:-}"
+	local path="$HOME"/.local/bin/"$name"
+
+	if ! _curl "$url" --output "$path"; then
+		fatal "failed to download '$name' from '$url'"
+	fi
+
+	chmod +x "$path"
 }
 
 # Prompt the user for their password with a custom message
diff --git a/lib/linux b/lib/linux
--- a/lib/linux
+++ b/lib/linux
@@ -13,20 +13,11 @@ message "  %s" "setting up Linux..."
 message "    %s" "installing essential tools..."
 if command -v apt-get > /dev/null; then
     sudo apt-get update > /dev/null
-    sudo apt-get install --yes build-essential curl file git > /dev/null
+    sudo apt-get install --yes build-essential curl file git jq > /dev/null
 else
     error "could not find a supported package manager; skipping install"
 fi
 message "    %s" "done installing essential tools."
-
-if ! command -v brew &> /dev/null; then
-    message "    %s" "installing Linuxbrew..."
-    set +eu
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
-    set -eu
-    eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
-    message "    %s" "done installing Linuxbrew."
-fi
 
 readonly fonts_dir="$(xdg_data)"/fonts
 if ! [ -d "$fonts_dir"/source-code-pro ]; then
@@ -40,5 +31,68 @@ if ! [ -d "$fonts_dir"/source-code-pro ]; then
 	fi
 	message '    %s' 'done installing Source Code Pro.'
 fi
+
+message "    %s" "installing shfmt..."
+if ! shfmt_url="$(get_release_url 'mvdan/sh' 'linux_amd64')"; then
+	fatal 'failed to get shfmt release URL'
+fi
+
+install_binary_from_url 'shfmt' "$shfmt_url"
+message "    %s" "done installing shfmt."
+
+message "    %s" "installing exa..."
+if ! exa_url="$(get_release_url 'ogham/exa' 'linux-x86_64')"; then
+	fatal 'failed to get exa release URL'
+fi
+
+exa_zip_tmp="$(mktemp)"
+if ! _curl "$exa_url" --output "$exa_zip_tmp"; then
+	fatal 'failed to download exa'
+fi
+
+exa_tmp="$(mktemp -d)"
+if ! unzip "$exa_zip_tmp" 'exa-linux-x86_64' -d "$exa_tmp" > /dev/null; then
+	fatal 'failed to unzip exa'
+fi
+rm -f "$exa_zip_tmp"
+
+exa_path="$HOME"/.local/bin/exa
+mv "$exa_tmp"/exa-linux-x86_64 "$exa_path"
+rm -rf "$exa_tmp"
+
+chmod +x "$exa_path"
+message "    %s" "done installing exa."
+
+message "    %s" "installing scc..."
+if ! scc_url="$(get_release_url 'boyter/scc' 'x86_64-unknown-linux')"; then
+	fatal 'failed to get scc release URL'
+fi
+
+scc_zip_tmp="$(mktemp)"
+if ! _curl "$scc_url" --output "$scc_zip_tmp"; then
+	fatal 'failed to download scc'
+fi
+
+scc_tmp="$(mktemp -d)"
+if ! unzip "$scc_zip_tmp" 'scc' -d "$scc_tmp" > /dev/null; then
+	fatal 'failed to unzip scc'
+fi
+rm -f "$scc_zip_tmp"
+
+scc_path="$HOME"/.local/bin/scc
+mv "$scc_tmp"/scc "$scc_path"
+rm -rf "$scc_tmp"
+
+chmod +x "$scc_path"
+message "    %s" "done installing scc."
+
+message "    %s" "installing Slack CLI..."
+slack_cli_path="$HOME"/.local/bin/slack
+if ! _curl https://raw.githubusercontent.com/rockymadden/slack-cli/master/src/slack --output "$slack_cli_path"; then
+	fatal 'failed to download Slack CLI'
+fi
+
+chmod +x "$slack_cli_path"
+message "    %s" "done installing Slack CLI."
 
 message "  %s" "done setting up Linux."
diff --git a/lib/node b/lib/node
--- a/lib/node
+++ b/lib/node
@@ -9,8 +9,39 @@ source "$_dir"/helpers
 
 message "setting up Node..."
 
+message "  %s" "installing Nodenv..."
+nodenv_root="${XDG_DATA_HOME:-$HOME/.local/share}"/nodenv
+mkdir -p "$nodenv_root"
+if ! [ -d "$nodenv_root" ]; then
+	if ! git clone https://github.com/nodenv/nodenv.git "$nodenv_root" > /dev/null; then
+		fatal 'failed to clone Nodenv'
+	fi
+fi
+
+eval "$("$nodenv_root"/bin/nodenv init -)"
+message "  %s" "done installing Nodenv."
+
+message "  %s" "installing Nodenv plugins..."
+mkdir -p "$nodenv_root"/plugins
+
+declare -a nodenv_plugins=(
+	node-build
+	nodenv-update
+	nodenv-default-packages
+	nodenv-package-rehash
+)
+
+for nodenv_plugin in "${nodenv_plugins[@]}"; do
+	if ! [ -d "$nodenv_root"/plugins/"$nodenv_plugin" ]; then
+		if ! git clone https://github.com/nodenv/"$nodenv_plugin".git "$nodenv_root"/plugins/"$nodenv_plugin" > /dev/null; then
+			fatal "failed to install Nodenv plugin '$nodenv_plugin'"
+		fi
+	fi
+done
+message "  %s" "done installing Nodenv plugins."
+
 message "  %s" "copying default packages file..."
-cp "$_dir"/../config/npm-default-packages "$(nodenv root)/default-packages" &>/dev/null || true
+cp "$_dir"/../config/npm-default-packages "$nodenv_root"/default-packages &> /dev/null || true
 message "  %s" "done copying default packages file."
 
 message "  %s" "getting latest Node version..."
@@ -23,16 +54,21 @@ message "  %s" "done getting latest Node version."
 
 if [ -n "$latest_node_version" ]; then
 	message "  %s" "installing Node $latest_node_version and default npm packages..."
-	nodenv install --force "$latest_node_version" &>/dev/null || true
-	nodenv global "$latest_node_version" || true
-	eval "$(nodenv init -)"
+	if ! nodenv install --skip-existing "$latest_node_version" &> /dev/null; then
+		fatal 'failed to install Node'
+	fi
+
+	if ! nodenv global "$latest_node_version"; then
+		fatal 'failed to set gloabl Node version'
+	fi
+
 	message "  %s" "done installing Node and default npm packages."
 else
 	warn "could not get latest Node version; installation failed"
 fi
 
 message "  %s" "setting Python path..."
-npm config set --global python "$(which python3)"
+npm config set --global python "$(command -v python3)"
 message "  %s" "done setting Python path."
 
 message "done setting up Node."
diff --git a/lib/zsh b/lib/zsh
--- a/lib/zsh
+++ b/lib/zsh
@@ -10,16 +10,18 @@ request-sudo
 
 if [[ "$SHELL" != *zsh ]]; then
 	message "changing default shell to Zsh..."
+	zsh_path="$(command -v zsh)"
+
 
 	if is-macos; then
-		sudo chsh -s "$(which zsh)" "$USER"
+		sudo chsh -s "$zsh_path" "$USER"
 	else
 		if ! grep 'zsh' /etc/shells >/dev/null; then
 			message "adding Zsh to /etc/shells..."
-			command -v zsh | sudo tee -a /etc/shells
+			echo "$zsh_path" | sudo tee -a /etc/shells
 			message "done adding Zsh to /etc/shells."
 		fi
-		chsh --shell "$(which zsh)"
+		chsh --shell "$zsh_path"
 	fi
 
 	message "done changing default shell to Zsh."
@@ -33,3 +35,12 @@ fi
 ln -sf "$_dir"/../zsh/* "$data_dir"
 ln -sf "$_dir"/../.zshrc "$HOME"
 message "done initializing Zsh configuration."
+
+z_path="$(xdg_data)"/zsh-z
+if ! [ -d "$z_path" ]; then
+	message "installing z..."
+	if ! git clone https://github.com/agkozak/zsh-z.git ; then
+		fatal 'failed to clone zsh-z'
+	fi
+	message "done installing z."
+fi
