Proceed when apt install fails

diff --git a/lib/apt b/lib/apt
--- a/lib/apt
+++ b/lib/apt
@@ -267,7 +267,9 @@ declare -a packages=(
 )
 
 log_start 'installing packages'
-sudo apt-get install --yes "${packages[@]}"
+if ! request_sudo apt-get install --yes "${packages[@]}"; then
+	warn 'failed to install apt packages; this may require manual resolution'
+fi
 log_end
 
 declare -a unwanted_packages=(
@@ -279,7 +281,7 @@ declare -a unwanted_packages=(
 
 log_start 'removing unwanted packages'
 for unwanted_package in "${unwanted_packages[@]}"; do
-	sudo apt-get remove --yes "$unwanted_package" &>/dev/null || true
+	request_sudo apt-get remove --yes "$unwanted_package" &>/dev/null || true
 done
 log_end
 
