Switch Delta to Catppuccin themes
Also remove the unnecessary `pager = less` configuration: Delta does
not use Bat as a pager, it just uses the Bat library for syntax
highlighting.

diff --git a/lib/git b/lib/git
--- a/lib/git
+++ b/lib/git
@@ -54,4 +54,11 @@ else
 	log_end
 fi
 
+log_start 'configuring Delta themes'
+if ! _curl https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig --output "$config_path"/delta-themes.gitconfig; then
+	fatal 'failed to download Delta themes'
+fi
+git config --global 'include.path' "$config_path"/delta-themes.gitconfig
+log_end
+
 log_end
