Manually install Hub to get latest version

diff --git a/lib/linux b/lib/linux
--- a/lib/linux
+++ b/lib/linux
@@ -95,4 +95,26 @@ fi
 chmod +x "$slack_cli_path"
 message "    %s" "done installing Slack CLI."
 
+message '  %s' 'installing Hub...'
+if ! hub_url="$(get_release_url 'github/hub' 'linux-amd64')"; then
+	fatal 'failed to get Hub release URL'
+fi
+hub_tmp="$(mktemp --suffix .tgz)"
+if ! _curl "$hub_url" --output "$hub_tmp"; then
+	fatal 'failed to download Hub'
+fi
+hub_extracted_tmp="$(mktemp -d)"
+if ! tar zxvf "$hub_tmp" -C "$hub_extracted_tmp" --strip-components=1 > /dev/null; then
+	fatal 'failed to extract Hub'
+fi
+rm -f "$hub_tmp"
+hub_path="$HOME"/.local/bin/hub
+install "$hub_extracted_tmp"/bin/hub "$hub_path"
+install "$hub_extracted_tmp"/share/man/*/*.1 "$HOME"/.local/share/man/man1
+hub_completion_dir="$HOME"/.local/share/hub
+mkdir -p "$hub_completion_dir"
+install "$hub_extracted_tmp"/etc/hub.zsh_completion "$hub_completion_dir"
+rm -rf "$hub_extracted_tmp"
+message '  %s' 'done installing Hub.'
+
 message "  %s" "done setting up Linux."
