Install websocat as binary instead of .deb

diff --git a/lib/linux-software b/lib/linux-software
--- a/lib/linux-software
+++ b/lib/linux-software
@@ -115,6 +115,17 @@ install "$ncspot_extracted_tmp"/ncspot "$ncspot_path"
 rm -rf "$ncspot_extracted_tmp"
 log_end
 
+log_start 'installing websocat'
+if ! websocat_url="$(get_release_url 'vi/websocat' '_linux64')"; then
+	fatal 'failed to get websocat release URL'
+fi
+websocat_path="$HOME/.local/bin/websocat"
+if ! _curl "$websocat_url" --output "$websocat_path"; then
+	fatal 'failed to download websocat'
+fi
+chmod +x "$websocat_path"
+log_end
+
 log_start 'installing YubiKey Manager'
 yubikey_manager_path="$HOME/.local/bin/YubiKey Manager.AppImage"
 if ! _curl 'https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-latest-linux.AppImage' \
