Add YubiKey Manager

diff --git a/lib/linux-software b/lib/linux-software
--- a/lib/linux-software
+++ b/lib/linux-software
@@ -126,4 +126,13 @@ fi
 chmod +x "$landrop_path"
 log_end
 
+log_start 'installing YubiKey Manager'
+yubikey_manager_path="$HOME/.local/bin/YubiKey Manager.AppImage"
+if ! _curl 'https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-latest-linux.AppImage' \
+	--output "$yubikey_manager_path"; then
+	fatal 'failed to download YubiKey Manager'
+fi
+chmod +x "$yubikey_manager_path"
+log_end
+
 log_end
