Add Jan

diff --git a/lib/linux-software b/lib/linux-software
--- a/lib/linux-software
+++ b/lib/linux-software
@@ -282,6 +282,12 @@ if is_ubuntu; then
 	fi
 	log_end
 
+	log_start 'installing Jan'
+	if ! install_deb_from_github_release 'menloresearch/jan' '_amd64.deb'; then
+		fatal 'failed to install Jan'
+	fi
+	log_end
+
 	log_start 'installing Obsidian'
 	if ! install_deb_from_github_release 'obsidianmd/obsidian-releases' '_amd64.deb'; then
 		fatal 'failed to install Obsidian'
