Add LANDrop

diff --git a/lib/linux-software b/lib/linux-software
--- a/lib/linux-software
+++ b/lib/linux-software
@@ -115,4 +115,15 @@ install "$ncspot_extracted_tmp"/ncspot "$ncspot_path"
 rm -rf "$ncspot_extracted_tmp"
 log_end
 
+log_start 'installing LANDrop'
+landrop_path="$HOME"/.local/bin/LANDrop.AppImage
+if ! landrop_url="$(get_release_url 'LANDrop/LANDrop' '.AppImage')"; then
+	fatal 'failed to get LANDrop release URL'
+fi
+if ! _curl "$landrop_url" --output "$landrop_path"; then
+	fatal 'failed to download LANDrop'
+fi
+chmod +x "$landrop_path"
+log_end
+
 log_end
