Move non-auto update .deb installation to `lib/linux-software`
Also move Bitwarden from Flatpak to .deb (Flatpak's sandbox makes
biometric login not work).

diff --git a/lib/linux-software b/lib/linux-software
--- a/lib/linux-software
+++ b/lib/linux-software
@@ -227,4 +227,61 @@ log_start 'installing YubiKey Manager'
 install_binary_from_url 'yubikey-manager' 'https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-latest-linux.AppImage'
 log_end
 
+# TODO test on a fresh system; will this work before running lib/apt and lib/ubuntu?
+if is_ubuntu; then
+	log_start 'installing balenaEtcher'
+	if ! install_deb_from_github_release 'balena-io/etcher' '_amd64.deb'; then
+		fatal 'failed to install balenaEtcher'
+	fi
+	log_end
+
+	log_start 'installing bat'
+	if ! install_deb_from_github_release 'sharkdp/bat' '_amd64.deb'; then
+		fatal 'failed to install bat'
+	fi
+	log_end
+
+	log_start 'installing Bitwarden'
+	if ! install_deb_from_url 'https://bitwarden.com/download/?app=desktop&platform=linux&variant=deb'; then
+		fatal 'failed to install Bitwarden'
+	fi
+	log_end
+
+	log_start 'installing git-delta'
+	if ! install_deb_from_github_release 'dandavison/delta' '_amd64.deb'; then
+		fatal 'failed to install git-delta'
+	fi
+	log_end
+
+	log_start 'installing glow'
+	if ! install_deb_from_github_release 'charmbracelet/glow' '_amd64.deb'; then
+		fatal 'failed to install glow'
+	fi
+	log_end
+
+	log_start 'installing Hugo'
+	if ! install_deb_from_github_release 'gohugoio/hugo' 'linux-amd64.deb'; then
+		fatal 'failed to install Hugo'
+	fi
+	log_end
+
+	log_start 'installing hyperfine'
+	if ! install_deb_from_github_release 'sharkdp/hyperfine' '_amd64.deb'; then
+		fatal 'failed to install hyperfine'
+	fi
+	log_end
+
+	log_start 'installing Obsidian'
+	if ! install_deb_from_github_release 'obsidianmd/obsidian-releases' '_amd64.deb'; then
+		fatal 'failed to install Obsidian'
+	fi
+	log_end
+
+	log_start 'installing pastel'
+	if ! install_deb_from_github_release 'sharkdp/pastel' '_amd64.deb'; then
+		fatal 'failed to install pastel'
+	fi
+	log_end
+fi
+
 log_end
