Switch from pipx to uv tool install

diff --git a/lib/linux-software b/lib/linux-software
--- a/lib/linux-software
+++ b/lib/linux-software
@@ -194,6 +194,26 @@ if ! install_binary_from_github_release 'undercutf1' 'JustAman62/undercut-f1' 'l
 fi
 log_end
 
+log_start 'installing uv'
+if ! uv_url="$(get_release_url 'astral-sh/uv' 'uv-x86_64-unknown-linux-gnu.tar.gz')"; then
+	fatal 'failed to get uv release URL'
+fi
+
+uv_tmp="$(mktemp)"
+if ! _curl "$uv_url" --output "$uv_tmp"; then
+	fatal 'failed to download uv'
+fi
+
+uv_extracted_tmp="$(mktemp -d)"
+if ! tar zxvf "$uv_tmp" --strip-components 1 -C "$uv_extracted_tmp" >/dev/null; then
+	fatal 'failed to extract uv'
+fi
+rm -f "$uv_tmp"
+
+install "$uv_extracted_tmp"/{uv,uvx} "$HOME"/.local/bin
+rm -rf "$uv_extracted_tmp"
+log_end
+
 log_start 'installing websocat'
 if ! install_binary_from_github_release 'websocat' 'vi/websocat' 'x86_64-unknown-linux-musl'; then
 	fatal 'failed to install websocat'
