Automatically configure Broot shell extension

diff --git a/lib/main b/lib/main
--- a/lib/main
+++ b/lib/main
@@ -79,4 +79,22 @@ fi
 "$_dir"/zsh
 "$_dir"/profile-picture
 
+
+if "$_dir"/../bin/is-macos; then
+  broot_root='org.dystroy.broot'
+else
+  broot_root='broot'
+fi
+broot_dir="$(xdg_config)"/"$broot_root"/launcher
+if command -v broot > /dev/null && ! [ -f "$broot_dir"/installed-v1 ]; then
+	message '  %s' 'installing broot shell function...'
+	broot_launcher_dir="$broot_dir"/bash
+	mkdir -p "$broot_launcher_dir"
+	if ! broot --print-shell-function zsh > "$broot_launcher_dir"/br; then
+		fatal 'failed to install broot shell function'
+	fi
+	broot --set-install-state installed
+	message '  %s' 'done installing broot shell function.'
+fi
+
 message "done. start a new login shell or run 'source .zshrc'."
