Revert "Use package manager for globally-installed version of Node"
This reverts commits 6cb286bd9e5aabcfbc8c69602117beef7e4d194d and
36b3a1e645bc29c1de6d744ed2a3ddcf82ff9300.

Switches back to using a nodenv-managed Node version instead of system
Node. The Node version is way too old on Ubuntu to make this practical.

diff --git a/lib/node b/lib/node
--- a/lib/node
+++ b/lib/node
@@ -63,14 +63,28 @@ fi
 log 'copying default packages file'
 cp "$_dir"/../config/npm-default-packages "$(nodenv root)"/default-packages &>/dev/null || true
 
-log_start 'installing default packages'
-if ! nodenv default-packages install system; then
-	warn 'failed to install one or more default packages'
-fi
-if ! nodenv default-packages install --all; then
-	warn 'failed to install one or more default packages'
-fi
+log_start 'getting latest Node version'
+# 1. Get list of Node versions
+# 2. Filter to only get normal Node versions, like "  9.5.0"
+# 3. Take last line of output which will be latest version
+# 4. Remove the leading spaces
+latest_node_version="$(nodenv install --list | grep -E '^[0-9\.]+$' | tail -1 | xargs)"
 log_end
+
+if [ -n "$latest_node_version" ]; then
+	log_start "installing Node $latest_node_version and default npm packages"
+	if ! nodenv install --skip-existing "$latest_node_version" &>/dev/null; then
+		fatal 'failed to install Node'
+	fi
+
+	if ! nodenv global "$latest_node_version"; then
+		fatal 'failed to set gloabl Node version'
+	fi
+
+	log_end
+else
+	warn "could not get latest Node version; installation failed"
+fi
 
 log_start 'setting Python path'
 # Must initialize Nodenv in order for npm to be available in PATH
