Only install Nodenv manually on Linux

diff --git a/lib/node b/lib/node
--- a/lib/node
+++ b/lib/node
@@ -9,39 +9,41 @@ source "$_dir"/helpers
 
 message "setting up Node..."
 
-message "  %s" "installing Nodenv..."
-nodenv_root="${XDG_DATA_HOME:-$HOME/.local/share}"/nodenv
-mkdir -p "$nodenv_root"
-if ! [ -d "$nodenv_root" ]; then
-	if ! git clone https://github.com/nodenv/nodenv.git "$nodenv_root" > /dev/null; then
-		fatal 'failed to clone Nodenv'
-	fi
-fi
-
-eval "$("$nodenv_root"/bin/nodenv init -)"
-message "  %s" "done installing Nodenv."
-
-message "  %s" "installing Nodenv plugins..."
-mkdir -p "$nodenv_root"/plugins
-
-declare -a nodenv_plugins=(
-	node-build
-	nodenv-update
-	nodenv-default-packages
-	nodenv-package-rehash
-)
-
-for nodenv_plugin in "${nodenv_plugins[@]}"; do
-	if ! [ -d "$nodenv_root"/plugins/"$nodenv_plugin" ]; then
-		if ! git clone https://github.com/nodenv/"$nodenv_plugin".git "$nodenv_root"/plugins/"$nodenv_plugin" > /dev/null; then
-			fatal "failed to install Nodenv plugin '$nodenv_plugin'"
+if "$_dir"/../bin/is-linux; then
+	message "  %s" "installing Nodenv..."
+	nodenv_root="${XDG_DATA_HOME:-$HOME/.local/share}"/nodenv
+	mkdir -p "$nodenv_root"
+	if ! [ -d "$nodenv_root" ]; then
+		if ! git clone https://github.com/nodenv/nodenv.git "$nodenv_root" > /dev/null; then
+			fatal 'failed to clone Nodenv'
 		fi
 	fi
-done
-message "  %s" "done installing Nodenv plugins."
+
+	eval "$("$nodenv_root"/bin/nodenv init -)"
+	message "  %s" "done installing Nodenv."
+
+	message "  %s" "installing Nodenv plugins..."
+	mkdir -p "$nodenv_root"/plugins
+
+	declare -a nodenv_plugins=(
+		node-build
+		nodenv-update
+		nodenv-default-packages
+		nodenv-package-rehash
+	)
+
+	for nodenv_plugin in "${nodenv_plugins[@]}"; do
+		if ! [ -d "$nodenv_root"/plugins/"$nodenv_plugin" ]; then
+			if ! git clone https://github.com/nodenv/"$nodenv_plugin".git "$nodenv_root"/plugins/"$nodenv_plugin" > /dev/null; then
+				fatal "failed to install Nodenv plugin '$nodenv_plugin'"
+			fi
+		fi
+	done
+	message "  %s" "done installing Nodenv plugins."
+fi
 
 message "  %s" "copying default packages file..."
-cp "$_dir"/../config/npm-default-packages "$nodenv_root"/default-packages &> /dev/null || true
+cp "$_dir"/../config/npm-default-packages "$(nodenv root)"/default-packages &> /dev/null || true
 message "  %s" "done copying default packages file."
 
 message "  %s" "getting latest Node version..."
