Fix bootstrap on macOS
- Source `.profile` in `lib/helpers` and `,bootstrap` so the `PATH` is
correct
- Add XDG directory variables to `.profile` so scripts can use them
before `.zshenv` is in place
- Add `node-build` and `nodenv/nodenv` tap
- Add Chrome
- Detect fresh macOS system correctly (`realpath` is now installed by
default)
- Run `brew shellenv` before attempting to install `brew` dependencies
in `,bootstrap`
- Add permissions to edit GPG keys with the GitHub CLI
- Handle already-set `gh` aliases
- Handle missing `tput dim` capability (macOS Terminal.app)
- Handle `ln` without `-r` flag
- Restore `lib/macos` script with up-to-date contents
- Handle failure to set npm Python configuration option

diff --git a/lib/node b/lib/node
--- a/lib/node
+++ b/lib/node
@@ -82,7 +82,9 @@ fi
 log_start 'setting Python path'
 # Must initialize Nodenv in order for npm to be available in PATH
 eval "$(nodenv init -)"
-npm config set python "$(command -v python3)"
+if ! npm config set python "$(command -v python3)"; then
+	warn 'failed to set npm Python configuration option'
+fi
 log_end
 
 if is_macos && [ -f "$NPM_CONFIG_USERCONFIG" ] && ! [ -h "$HOME"/.npmrc ]; then
