Switch from zsh-syntax-highlighting to fast-syntax-highlighting

diff --git a/lib/zsh b/lib/zsh
--- a/lib/zsh
+++ b/lib/zsh
@@ -43,3 +43,12 @@ if ! [ -d "$z_path" ]; then
 	fi
 	message "done installing z."
 fi
+
+fast_syntax_highlighting_path="$(xdg_data)"/zsh-fast-syntax-highlighting
+if ! [ -d "$fast_syntax_highlighting_path" ]; then
+	message "installing Fast Syntax Highlighting..."
+	if ! git clone --depth 1 https://github.com/zdharma/fast-syntax-highlighting.git "$fast_syntax_highlighting_path" > /dev/null; then
+		fatal 'failed to clone Fast Syntax Highlighting'
+	fi
+	message "done installing Fast Syntax Highlighting."
+fi
